apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mayacli
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : maya-cli
    spec:
      containers:
        - name: maya-cli
          image: mulebot/cli:test
          imagePullPolicy: Always

